### ISSUE TITLE
Erro de digitação no campo "CARACTERIZAÇÃO"

### ISSUE THREAD

**Issue by LuwkasLima** [brainwp/contatospolis#11]
Erro de digitação no campo "CARACTERIZAÇÃO"

![image](https://cloud.githubusercontent.com/assets/5949986/12988559/eb33295c-d0c6-11e5-89cc-7f89831765d6.png)

**Comment by diogosp** [comment]
Problema persiste @LuwkasLima e @matheusgimenez

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
@diogosp podemos fechar essa issue? Chegou a ir pra PROD?

**Comment by diogosp** [comment]
Num tenho a mínima ideia, acredito que sim...
